In [1]:
import requests
import json
import pandas as pd
import pymongo
from sqlalchemy import create_engine

# NASA API Key
NASA_API_KEY = "Nm3taoik7basPrWezhZUedq9CPxOALUiheRz4biR"

print("Libraries imported!")

Libraries imported!

In [9]:
# Checking what the API is returning
url = f"https://api.nasa.gov/DONKI/FLR?startDate=2010-01-01&endDate=2024-01-01&api_key={NASA_API_KEY}"

response = requests.get(url)

print("Status Code:", response.status_code)
print("Response text (first 500 chars):")
print(response.text[:500])

Status Code: 200
Response text (first 500 chars):
[{"flrID":"2010-04-03T09:04:00-FLR-001","catalog":"M2M_CATALOG","instruments":[{"displayName":"GOES14: SEM/XRS 1.0-8.0"}],"beginTime":"2010-04-03T09:04Z","peakTime":"2010-04-03T09:54Z","endTime":"2010-04-03T10:58Z","classType":"B7.4","sourceLocation":"S25W03","activeRegionNum":11059,"note":"","submissionTime":"2015-06-16T18:47Z","versionId":1,"link":"https://webtools.ccmc.gsfc.nasa.gov/DONKI/view/FLR/8665/-1","linkedEvents":[{"activityID":"2010-04-03T09:54:00-CME-001"}],"sentNotifications":null}

In [11]:
# ============================================
# FETCHING NASA SPACE MISSIONS VIA API
# ============================================
# Purpose: Retrieve solar flare data from
# the NASA DONKI REST API
# Source: https://api.nasa.gov/
# ============================================

# NASA DONKI API - Space Weather & Mission Events
url = f"https://api.nasa.gov/DONKI/FLR?startDate=2010-01-01&endDate=2024-01-01&api_key={NASA_API_KEY}"

response = requests.get(url)
data = response.json()

print("Status Code:", response.status_code)
print("Total records fetched:", len(data))
print("\nSample record:")
print(json.dumps(data[0], indent=2))

Status Code: 200
Total records fetched: 1468

Sample record:
{
  "flrID": "2010-04-03T09:04:00-FLR-001",
  "catalog": "M2M_CATALOG",
  "instruments": [
    {
      "displayName": "GOES14: SEM/XRS 1.0-8.0"
    }
  ],
  "beginTime": "2010-04-03T09:04Z",
  "peakTime": "2010-04-03T09:54Z",
  "endTime": "2010-04-03T10:58Z",
  "classType": "B7.4",
  "sourceLocation": "S25W03",
  "activeRegionNum": 11059,
  "note": "",
  "submissionTime": "2015-06-16T18:47Z",
  "versionId": 1,
  "link": "https://webtools.ccmc.gsfc.nasa.gov/DONKI/view/FLR/8665/-1",
  "linkedEvents": [
    {
      "activityID": "2010-04-03T09:54:00-CME-001"
    }
  ],
  "sentNotifications": null
}

In [13]:
# Saving raw API data to file (backup)
with open(r"C:\Users\karum\Downloads\SpaceProject\data\nasa_donki_raw.json", "w") as f:
    json.dump(data, f, indent=2)

print(f"Saved {len(data)} records to nasa_donki_raw.json")

Saved 1468 records to nasa_donki_raw.json

In [31]:
# Connecting to MongoDB and store raw JSON data
client = pymongo.MongoClient("mongodb://localhost:27017/")
db = client["space_project"]
collection = db["nasa_solar_flares"]

# Clearing previous data if re-running
collection.delete_many({})

# Inserting all records
result = collection.insert_many(data)
print(f"   Inserted {len(result.inserted_ids)} records into MongoDB")
print(f"   Database: space_project")
print(f"   Collection: nasa_solar_flares")

   Inserted 1468 records into MongoDB
   Database: space_project
   Collection: nasa_solar_flares

In [33]:
# Reading data back from MongoDB into pandas
records = list(collection.find({}, {"_id": 0}))
df_nasa = pd.DataFrame(records)

print(f"  Loaded {len(df_nasa)} records from MongoDB")
print(f"\nColumns ({len(df_nasa.columns)}):")
print(df_nasa.columns.tolist())
print(f"\nFirst 3 rows:")
df_nasa.head(3)

  Loaded 1468 records from MongoDB

Columns (15):
['flrID', 'catalog', 'instruments', 'beginTime', 'peakTime', 'endTime', 'classType', 'sourceLocation', 'activeRegionNum', 'note', 'submissionTime', 'versionId', 'link', 'linkedEvents', 'sentNotifications']

First 3 rows:

,flrID,catalog,instruments,beginTime,peakTime,endTime,classType,sourceLocation,activeRegionNum,note,submissionTime,versionId,link,linkedEvents,sentNotifications
0,2010-04-03T09:04:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES14: SEM/XRS 1.0-8.0'}],2010-04-03T09:04Z,2010-04-03T09:54Z,2010-04-03T10:58Z,B7.4,S25W03,11059.0,,2015-06-16T18:47Z,1,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,[{'activityID': '2010-04-03T09:54:00-CME-001'}],None
1,2010-06-12T00:30:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES14: SEM/XRS 1.0-8.0'}],2010-06-12T00:30Z,2010-06-12T00:57Z,2010-06-12T01:02Z,M2.0,N22W43,11081.0,,2013-07-18T19:15Z,2,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,None,"[{'messageID': '20100612-AL-001', 'messageIssu..."
2,2010-08-07T17:55:00-FLR-001,M2M_CATALOG,[{'displayName': 'GOES14: SEM/XRS 1.0-8.0'}],2010-08-07T17:55Z,2010-08-07T18:24Z,2010-08-07T18:47Z,M1.0,N14E37,11093.0,,2015-07-16T19:02Z,2,https://webtools.ccmc.gsfc.nasa.gov/DONKI/view...,None,"[{'messageID': '20100807-AL-001', 'messageIssu..."

In [35]:
# ============================================
# DATA CLEANING & TRANSFORMATION
# ============================================
# Purpose: Cleaning the raw NASA solar flare data
# and preparing it for storage in PostgreSQL
# ============================================

# Making a copy so we don't change the original data
df_clean = df_nasa.copy()

# --- Step 1: Converting date columns from text to proper datetime format ---
df_clean['beginTime'] = pd.to_datetime(df_clean['beginTime'], errors='coerce')
df_clean['peakTime'] = pd.to_datetime(df_clean['peakTime'], errors='coerce')
df_clean['endTime'] = pd.to_datetime(df_clean['endTime'], errors='coerce')
df_clean['submissionTime'] = pd.to_datetime(df_clean['submissionTime'], errors='coerce')

# --- Step 2: Creating new useful columns from existing data ---
# Extracting the year and month from the begin time
df_clean['year'] = df_clean['beginTime'].dt.year
df_clean['month'] = df_clean['beginTime'].dt.month

# Calculating how long each solar flare lasted (in minutes)
duration = df_clean['endTime'] - df_clean['beginTime']
df_clean['duration_minutes'] = duration.dt.total_seconds() / 60

# Extracting the flare class letter (B, C, M, or X)
# Solar flares are classified as B, C, M, X where X is the strongest
df_clean['flare_class'] = df_clean['classType'].str[0]

# Extracting the flare intensity number (e.g., from "M2.0" extract 2.0)
df_clean['flare_intensity'] = pd.to_numeric(df_clean['classType'].str[1:], errors='coerce')

# --- Step 3: Removing columns that contain nested/complex data ---
# These columns have lists/dicts inside them which don't work in SQL
columns_to_drop = ['instruments', 'linkedEvents', 'link', 'sentNotifications']
df_clean = df_clean.drop(columns=columns_to_drop, errors='ignore')

# --- Step 4: Removing rows where essential data is missing ---
df_clean = df_clean.dropna(subset=['beginTime', 'classType'])

# --- Step 5: Reset the row index after dropping rows ---
df_clean = df_clean.reset_index(drop=True)

# --- Print summary of cleaned data ---
print(f"Cleaned dataset: {len(df_clean)} records, {len(df_clean.columns)} columns")
print(f"\nColumn names: {df_clean.columns.tolist()}")
print(f"\nFlare class distribution:")
print(df_clean['flare_class'].value_counts())
print(f"\nYear range: {df_clean['year'].min()} to {df_clean['year'].max()}")
print(f"\nMissing values per column:")
print(df_clean.isnull().sum())

Cleaned dataset: 1468 records, 16 columns

Column names: ['flrID', 'catalog', 'beginTime', 'peakTime', 'endTime', 'classType', 'sourceLocation', 'activeRegionNum', 'note', 'submissionTime', 'versionId', 'year', 'month', 'duration_minutes', 'flare_class', 'flare_intensity']

Flare class distribution:
flare_class
M    1046
C     306
X      71
B      44
A       1
Name: count, dtype: int64

Year range: 2010 to 2024

Missing values per column:
flrID                 0
catalog               0
beginTime             0
peakTime              0
endTime              42
classType             0
sourceLocation        0
activeRegionNum     108
note                  0
submissionTime        0
versionId             0
year                  0
month                 0
duration_minutes     42
flare_class           0
flare_intensity       0
dtype: int64

In [37]:
# ============================================
# CREATE POSTGRESQL DATABASE
# ============================================
# Purpose: Create the 'space_project' database
# NOTE: Only run this cell ONCE. If the database
# already exists, skip this cell.
# ============================================

from sqlalchemy import text

try:
    temp_engine = create_engine("postgresql://postgres:admin123@localhost:5432/postgres")
    with temp_engine.connect() as conn:
        conn.execution_options(isolation_level="AUTOCOMMIT")
        conn.execute(text("CREATE DATABASE space_project"))
    print("Database 'space_project' created successfully")
except Exception as e:
    print("Database 'space_project' already exists - skipping creation

Database 'space_project' already exists - skipping creation

In [39]:
# ============================================
# STORE CLEANED DATA IN POSTGRESQL
# ============================================
# Purpose: Save the cleaned solar flare data
# into the PostgreSQL database as a table
# ============================================

# Connect to our new space_project database
engine = create_engine("postgresql://postgres:admin123@localhost:5432/space_project")

# Save the cleaned dataframe as a table called 'nasa_solar_flares'
# if_exists='replace' means it will overwrite if we run this again
df_clean.to_sql('nasa_solar_flares', engine, if_exists='replace', index=False)

print(f"Stored {len(df_clean)} records in PostgreSQL")
print(f"Database: space_project")
print(f"Table: nasa_solar_flares")

Stored 1468 records in PostgreSQL
Database: space_project
Table: nasa_solar_flares

In [41]:
# ============================================
# VERIFY DATA IN POSTGRESQL
# ============================================
# Purpose: Read the data back from PostgreSQL
# to confirm it was stored correctly
# ============================================

# Read the table back from PostgreSQL
df_check = pd.read_sql("SELECT * FROM nasa_solar_flares", engine)

print(f"Read {len(df_check)} records from PostgreSQL")
print(f"\nFirst 3 rows:")
df_check.head(3)

Read 1468 records from PostgreSQL

First 3 rows:

,flrID,catalog,beginTime,peakTime,endTime,classType,sourceLocation,activeRegionNum,note,submissionTime,versionId,year,month,duration_minutes,flare_class,flare_intensity
0,2010-04-03T09:04:00-FLR-001,M2M_CATALOG,2010-04-03 09:04:00+00:00,2010-04-03 09:54:00+00:00,2010-04-03 10:58:00+00:00,B7.4,S25W03,11059.0,,2015-06-16 18:47:00+00:00,1,2010,4,114.0,B,7.4
1,2010-06-12T00:30:00-FLR-001,M2M_CATALOG,2010-06-12 00:30:00+00:00,2010-06-12 00:57:00+00:00,2010-06-12 01:02:00+00:00,M2.0,N22W43,11081.0,,2013-07-18 19:15:00+00:00,2,2010,6,32.0,M,2.0
2,2010-08-07T17:55:00-FLR-001,M2M_CATALOG,2010-08-07 17:55:00+00:00,2010-08-07 18:24:00+00:00,2010-08-07 18:47:00+00:00,M1.0,N14E37,11093.0,,2015-07-16 19:02:00+00:00,2,2010,8,52.0,M,1.0